<a href="https://colab.research.google.com/github/wasimnawaz1/programming_4_AI/blob/main/Programming_for_AI%2C_Lectures_(Week_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 4: Introduction to **AI271 Programming for AI**

### **Link to find the lecture:**
https://github.com/wasimnawaz1/programming_4_AI

### **NumPy** Library: The Core of Scientific Computing


- NumPy (Numerical Python) is crucial for efficient numerical operations in
machine learning.
- It provides powerful array objects and tools for working
with them.

- Arrays are faster and more memory-efficient than Python lists
for numerical computations.


         Let's create NumPy arrays, also known as vectors
         (1D arrays) and matrices (2D arrays),
         and perform some basic operations.

In [ ]:
import numpy as np

# --- Creating NumPy Arrays ---

# **Creating a 1D Array (Vector)**
# A 1D array is simply a sequence of numbers, often representing features or data points.


vector_a = np.array([5, 10, 15, 20])
vector_b = np.array([10, 20, 30, 40])

print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")

Vector A: [ 5 10 15 20]
Vector B: [10 20 30 40]


In [ ]:
# Example: Creating a vector of zeros
zeros_vector = np.zeros(10)
print(f"Vector of zeros: {zeros_vector}")

# Example: Creating a vector with a range of values
range_vector = np.arange(0, 1, 0.2) # Start, Stop (exclusive), Step
print(f"Vector with range: {range_vector}")


# range() can't give us values in floating point
# print(list(range(0, 1, 0.2)))

Vector of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Vector with range: [0.  0.2 0.4 0.6 0.8]


TypeError: 'float' object cannot be interpreted as an integer

### **Creating a 2D Array (Matrix)**
- A 2D array, or matrix, is a grid of numbers with rows and columns.
- They are essential for representing datasets, where rows are samples and columns are features.

In [ ]:
matrix_A = np.array([  [1, 2.5, 5] , [3, 4, 8] ])
print("\nMatrix A:")
print(matrix_A)

# Example: Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix (3x3):")
print(identity_matrix)

# Example: Creating a matrix of ones
ones_matrix = 5*np.ones((4, 5)) # (rows, columns)
print("\nMatrix of ones (2x3):")
print(ones_matrix)


Matrix A:
[[1.  2.5 5. ]
 [3.  4.  8. ]]

Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix of ones (2x3):
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:

# Array Attributes ---
# Understanding array dimensions and type.
vector_a = np.array([5, 10.5, 15, 20])
matrix_A = np.array([  [1, 2.5, 5] , [3, 4, 8] ])


print(f"\nShape of vector_a: {vector_a.shape} (1D array)")
print(f"Dimensions of vector_a: {vector_a.ndim}")
print(f"Data type of vector_a elements: {vector_a.dtype}")

print(f"Shape of matrix_A: {matrix_A.shape} ")   # (2 rows, 3 columns)
print(f"Dimensions of matrix_A: {matrix_A.ndim}")



Shape of vector_a: (4,) (1D array)
Dimensions of vector_a: 1
Data type of vector_a elements: float64
Shape of matrix_A: (2, 3) 
Dimensions of matrix_A: 2


In [ ]:
# Basic Array Operations ---

# **Element-wise Addition**
# This operation adds corresponding elements of two arrays.
vector_a = np.array([5, 15, 15, 20])
vector_b = np.array([10, 20, 30, 40])

vector_sum = vector_a + vector_b
print(f"\nSum of vectors (element-wise): {vector_sum}")

# Example: Element-wise multiplication
vector_product = vector_a * vector_b
print(f"Product of vectors (element-wise): {vector_product}")



Sum of vectors (element-wise): [15 35 45 60]
Product of vectors (element-wise): [ 50 300 450 800]


### **Dot Product (Matrix Multiplication)**
- The dot product is a fundamental operation in linear algebra, widely used in ML.
- For two vectors `[a1, a2, a3]` and `[b1, b2, b3]`, the dot product is `a1*b1 + a2*b2 + a3*b3`.

In [ ]:
vector_a = np.array([5, 15, 15, 20])
vector_b = np.array([10, 20, 30, 40])
dot_product = np.dot(vector_a, vector_b)
print(f"Dot product of vectors: {dot_product}")


matrix_A = np.array([  [1, 6] , [3, 8] ])

# Example: Matrix multiplication
matrix_B = np.array([  [3, 4], [6, 7]  ] )
print(f"\n\n\nmatrix_B:", matrix_B)

#  A  (2, 3)   B (2,2)
matrix_product = np.dot(matrix_A, matrix_B)
print("\nMatrix A * Matrix B (dot product):")
print(matrix_product)


Dot product of vectors: 1600



matrix_B: [[3 4]
 [6 7]]

Matrix A * Matrix B (dot product):
[[39 46]
 [57 68]]


In [ ]:
# Indexing and Slicing ---
# Accessing elements or sub-arrays.

my_array = np.array([5, 6, 7, 8])
print(f"\nOriginal array for indexing: {my_array}")
print(f"First element: {my_array[0]}")
print(f"Last element: {my_array[-1]}")
print(f"Elements from index 2 to 4 (exclusive): {my_array[2:4]}")
print(f"Elements from beginning to index 3 (exclusive): {my_array[:3]}")



my_matrix = np.array([ [1,2,3], [4,5,6], [7,8,9]  ])
print("\n\n\nOriginal matrix for indexing:")
print(my_matrix)
print(f"Element at row 1, column 2: {my_matrix[1, 2]}") # (row, column)
print(f"First row: {my_matrix[0, :]}") # All columns in row 0
print(f"Second column: {my_matrix[:, 1]}") # All rows in column 1
print(f"Sub-matrix (rows 0-1, columns 1-2): {my_matrix[0:2, 1:3]}")



Original array for indexing: [5 6 7 8]
First element: 5
Last element: 8
Elements from index 2 to 4 (exclusive): [7 8]
Elements from beginning to index 3 (exclusive): [5 6 7]






Original matrix for indexing:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Sub-matrix (rows 0-1, columns 1-2): [[2 3]
 [5 6]]


In [ ]:
# Reshaping Arrays ---
# Changing the dimensions of an array.
flat_array = np.arange(1, 11) #
print(f"\nFlat array: {flat_array}")


reshaped_matrix = flat_array[:8].reshape(4,2)
print("\n\n\nReshaped into 3x3 matrix:")
print(reshaped_matrix)



Flat array: [ 1  2  3  4  5  6  7  8  9 10]





Reshaped into 3x3 matrix:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Numpy for Mathematics used in AI
NumPy's capabilities extend far beyond these basic examples, including advanced linear algebra, Fourier transforms, and random number capabilities, making it an indispensable tool for scientific computing.

- Understanding key mathematical concepts is crucial for grasping how AI and machine learning algorithms work under the hood. We will use NumPy and Matplotlib libraries to demonstrate these concepts.

- **Goal:** Gain a practical understanding of Linear Algebra, Calculus, and Probability as used in AI and in machine learning.


In [ ]:
# ### Importing Essential Libraries
# # We'll start by importing `numpy` for numerical operations and `matplotlib.pyplot` for plotting.
# ## 1. Linear Algebra: The Language of Data
## Linear algebra is fundamental to machine learning as it provides a way to represent and manipulate data efficiently. Data points are often represented as **vectors**, and datasets as **matrices**. We'll use **NumPy** to perform fundamental linear algebra operations.
import numpy as np #
import matplotlib.pyplot as plt #

print("Libraries imported successfully!")



### Vectors
- A vector can be thought of as a 1D array of numbers.



In [ ]:
# Let's create 1D arrays (vectors) and perform element-wise addition and a dot product.
vector_a = np.array([-9, 8, 45]) #
vector_b = np.array([3, -7, 2]) #

print(f"Vector A: {vector_a}") #
print(f"Vector B: {vector_b}") #

# Element-wise addition
vector_sum = vector_a + vector_b #
print(f"Sum of vectors: {vector_sum}") #

# Dot product
dot_product = np.dot(vector_a, vector_b) #
print(f"Dot product of vectors: {dot_product}") #

### Scalar Multiplication and Vector Subtraction
- Vectors can be multiplied by a scalar (a single number) and subtracted from each other.


In [ ]:
scalar = 2
vector_c = np.array([5, 9, 0, -4])
vector_d = np.array([10, 20, -30, 40])

# Scalar multiplication
scalar_mul_a = scalar * vector_a
print(f"Scalar multiplication (2 * Vector A): {scalar_mul_a}")

# Vector subtraction
vector_diff = vector_c - vector_d
print(f"Difference of vectors (Vector C - Vector D): {vector_diff}")


### Vector Magnitude (L2 Norm)
- The magnitude or L2 norm of a vector represents its length.


In [ ]:
vector_e = np.array(  [4, -9] ) # A 2D vector for simple visualization
magnitude_e = np.linalg.norm(vector_e)     ### np.sqrt(4*4+   (-9*-9))
print(f"Vector E: {vector_e}")
print(f"Magnitude of Vector E: {magnitude_e:.2f}")


###  Matrices
- A matrix is a 2D array of numbers. They are crucial for representing transformations and complex datasets.



In [ ]:
# Create a 2D array (matrix)
matrix_A = np.array([    [4, -9],[5, 7]   ]) #
matrix_B = np.array([    [0, 5],[6, -8]   ]) #

print("\nMatrix A:") #
print(matrix_A) #
print("\nMatrix B:") #
print(matrix_B) #



In [ ]:
# Matrix addition is performed element-wise.

matrix_C = matrix_A + matrix_B #
print(f"\nMatrix A + B:\n{matrix_C}") #

# **Example 1.2.3: Matrix Multiplication (Dot Product)**
#
# Matrix multiplication is not element-wise. It follows specific rules of row-column dot products.

matrix_D = np.dot(matrix_A, matrix_B) #
print(f"\nMatrix A * B:\n{matrix_D}") #


In [ ]:
# Determinant and Inverse of a Matrix
## The **determinant** is a scalar value that provides insights into a square matrix, such as whether it's invertible. The **inverse** of a matrix, if it exists, is another matrix that when multiplied by the original, yields the identity matrix.
## **Note:** The inverse only exists for square matrices with a non-zero determinant.

determinant_A = np.linalg.det(matrix_A) #
inverse_A = np.linalg.inv(matrix_A) #
print(f"\nDeterminant of A: {determinant_A:.2f}") #
print(f"\nInverse of A:\n{inverse_A}") #

# Let's verify the inverse: A * A_inverse should be close to the identity matrix
identity_check = np.dot(matrix_A, inverse_A)
print(f"\nVerification (A * Inverse_A):\n{identity_check}")

# Example of a singular matrix (determinant is 0, so no inverse)
singular_matrix = np.array([[1,2], [2,4]])
determinant_singular = np.linalg.det(singular_matrix)
print(f"\nDeterminant of a singular matrix:\n{singular_matrix}")
print(f"Determinant: {determinant_singular:.2f}")
try:
    np.linalg.inv(singular_matrix)
except np.linalg.LinAlgError as e:
    print(f"Error trying to compute inverse of singular matrix: {e}")



In [ ]:
# Transpose of a Matrix
## The transpose of a matrix is obtained by flipping the matrix over its diagonal, i.e., interchanging the rows and columns.

matrix_F = np.array([1,2,3,4,5,6]).reshape([2,3])
print(f"\nOriginal Matrix F:\n{matrix_F}")

matrix_F_transpose = matrix_F.T
print(f"Transpose of Matrix F:\n{matrix_F_transpose}")



### **Calculus**: The Study of Change
- Calculus, particularly **derivatives** (or gradients), is vital in AI and for training machine learning models.
- Algorithms like gradient descent use derivatives to find the optimal parameters that minimize a model's error.
- We can use NumPy to approximate gradients.


In [ ]:
### Approximating Gradients (Derivatives)
## The `np.gradient()` function numerically approximates the derivative of a function.

# **Example 2.1.1: Gradient of a Quadratic Function**
# # We'll use the example provided in the source: `f(x) = x^2 + 2x + 1`. The true derivative is `f'(x) = 2x + 2`.

# Define a simple quadratic function
def f(x): #
    return x**2 + 2*x + 1 #

# Generate x values
x = np.linspace(-10, 10, 100) #
y = f(x) #

# Calculate the gradient (derivative)
gradient_f = np.gradient(y, x) #

# Plot the function and its gradient
plt.figure(figsize=(10, 6)) #
plt.plot(x, y, label='f(x) = x^2 + 2x + 1') #
plt.plot(x, gradient_f, label="f'(x) - Gradient (Numerical)", linestyle='--') #
plt.title('Function and its Gradient') #
plt.xlabel('x') #
plt.ylabel('y') #
plt.legend() #
plt.grid(True) #
plt.show() #


In [ ]:
# Gradient of a Cubic Function
## Let's explore another function: `g(x) = x^3 - 6x^2 + 9x + 1`. The true derivative is `g'(x) = 3x^2 - 12x + 9`.


# Define a cubic function
def g(x):
    return x**3 - 6*x**2 + 9*x + 1

# Generate x values
x_g = np.linspace(-2, 5, 100)
y_g = g(x_g)

# Calculate the gradient
gradient_g = np.gradient(y_g, x_g)

# Plot the function and its gradient
plt.figure(figsize=(10, 6))
plt.plot(x_g, y_g, label='g(x) = x^3 - 6x^2 + 9x + 1')
plt.plot(x_g, gradient_g, label="g'(x) - Gradient (Numerical)", linestyle='--')
plt.title('Cubic Function and its Gradient')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()



In [ ]:
# Gradient of a Trigonometric Function
## Consider `h(x) = sin(x)`. The true derivative is `h'(x) = cos(x)`.

# Define a trigonometric function
def h(x):
    return np.sin(x)

# Generate x values
x_h = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y_h = h(x_h)

# Calculate the gradient
gradient_h = np.gradient(y_h, x_h)

# Plot the function and its gradient
plt.figure(figsize=(10, 6))
plt.plot(x_h, y_h, label='h(x) = sin(x)')
plt.plot(x_h, gradient_h, label="h'(x) - Gradient (Numerical)", linestyle='--')
plt.title('Sine Function and its Gradient')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()


### =========================
### Practice Questions  (DEVELOP CODE)
### =========================


Q1. Create a NumPy array from a list and return its mean, max, and min.

Q2. Generate a NumPy array of numbers 1-20 and reshape it into 4x5 matrix.

Q3. Using slicing, extract:
  - first row
  - last column
  - submatrix (middle 2x3)

Q4. Create a NumPy array and replace all even numbers with 0.

Q5. Write a function that takes a NumPy array and returns squared values using vectorization.

Q6. Create two NumPy arrays and compute element-wise addition, multiplication, and dot product.

Q7. Use boolean indexing to extract values greater than mean from a NumPy array.


In [1]:
# =========================
# SOLUTIONS
# =========================

print("\n\nSOLUTIONS:\n")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Q1
arr = np.array([1,2,3,4,5])
print("Q1:", arr.mean(), arr.max(), arr.min())

# Q2
arr = np.arange(1,21).reshape(4,5)
print("Q2:\n", arr)

# Q3
print("Q3:")
print(arr[0])
print(arr[:,-1])
print(arr[1:3,1:4])

# Q4
arr = np.arange(10)
arr[arr%2==0] = 0
print("Q4:", arr)

# Q5
def square(arr):
    return arr**2
print("Q5:", square(np.array([1,2,3])))

# Q6
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Q6:", a+b, a*b, np.dot(a,b))

# Q7
arr = np.array([10,20,30,40])
print("Q7:", arr[arr > arr.mean()])




SOLUTIONS:

Q1: 3.0 5 1
Q2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Q3:
[1 2 3 4 5]
[ 5 10 15 20]
[[ 7  8  9]
 [12 13 14]]
Q4: [0 1 0 3 0 5 0 7 0 9]
Q5: [1 4 9]
Q6: [5 7 9] [ 4 10 18] 32
Q7: [30 40]
